version: "3.8"

services:
  api_gateaway:
    env_file:
      - .env
    volumes:
      - ./src:/app/src                # Monte uniquement le dossier src (code source)
      - /app/node_modules            # Volume anonyme pour node_modules dans le conteneur
      - ./tsconfig.json:/app/tsconfig.json:ro  # Monter tsconfig pour dev TypeScript (en lecture seule)
      - ./package.json:/app/package.json:ro    # Monter package.json seul, si vraiment nécessaire (parfois pas utile)
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npx nodemon --watch src --ext ts,json --exec ts-node src/index.ts